### ISSUE TITLE
deprecated customFds option in child_process

### ISSUE THREAD

**Issue by beriberikix** [bryan-m-hughes/raspi-io#17]
Got the following soft warning when installing: `child_process: customFds option is deprecated, use stdio instead.` Looking on the internetz, it seems the only reason not to migrate is that would break [NodeJS 0.4.x support](https://github.com/mochajs/mocha/pull/1287).

**Comment by bryan-m-hughes** [comment]
I've noticed that as well. The issue isn't with raspi-io, but rather with [node-gyp](https://github.com/TooTallNate/node-gyp) which I use to compile the C++ bits. See https://github.com/TooTallNate/node-gyp/pull/533
